on:
  workflow_dispatch:
  push:
    branches: [master]
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
  pull_request:
    branches: [master]

name: Test on Linux
jobs:
  test-linux:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        language: ["cpp"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install build dependencies
        run: "sudo apt-get update && sudo apt-get install git build-essential cmake libx11-dev libxtst-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev libglfw3-dev"

      - name: Compile
        run: "mkdir build && cd build && cmake .. -Dimgui_backend=GLFW -Dimgui_render=OpenGL3 -Dimgui_example=ON && cmake --build . --config Release"